project_id = "bqyfqycrxgchjkixugie"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.delete-account]
    verify_jwt = true
  [functions.revenuecat-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
